"""
AI Detection Module for Dubplate Authentication.

This module provides functionality to detect AI-generated audio content,
helping to distinguish authentic dubplates from AI-produced imitations.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional

import numpy as np


class AudioOrigin(Enum):
    """Classification of audio origin."""
    
    HUMAN = "human"
    AI_GENERATED = "ai_generated"
    AI_ENHANCED = "ai_enhanced"
    SOUND_ALIKE = "sound_alike"
    UNKNOWN = "unknown"


@dataclass
class AIDetectionResult:
    """Result of AI detection analysis."""
    
    origin: AudioOrigin
    ai_probability: float
    confidence: float
    analysis_details: dict
    artifacts_detected: list


class AIDetector:
    """
    AI-generated audio detection system.
    
    Analyzes audio to determine if it was generated by AI or created
    by human artists. Uses various acoustic markers and patterns
    that distinguish AI-generated content.
    """
    
    def __init__(self, sensitivity: float = 0.7):
        """
        Initialize the AI Detector.
        
        Args:
            sensitivity: Detection sensitivity (0.0-1.0), higher values
                        make detection more aggressive
        """
        self.sensitivity = min(max(sensitivity, 0.0), 1.0)
        
        # Known AI generation artifacts patterns
        self.artifact_patterns = {
            "spectral_smoothness": 0.85,  # AI tends to produce smoother spectra
            "micro_timing_variance": 0.02,  # AI has more consistent timing
            "harmonic_regularity": 0.9,  # AI produces more regular harmonics
            "transient_consistency": 0.95,  # AI transients are more consistent
        }
    
    def detect(self, audio_data: np.ndarray, sr: int = 22050) -> AIDetectionResult:
        """
        Analyze audio to detect AI generation.
        
        Args:
            audio_data: Audio samples as numpy array
            sr: Sample rate of the audio
            
        Returns:
            AIDetectionResult with detection analysis
        """
        # Perform various analyses
        spectral_analysis = self._analyze_spectral_characteristics(audio_data, sr)
        timing_analysis = self._analyze_timing_patterns(audio_data, sr)
        harmonic_analysis = self._analyze_harmonics(audio_data, sr)
        transient_analysis = self._analyze_transients(audio_data, sr)
        
        # Combine analyses
        analysis_details = {
            "spectral": spectral_analysis,
            "timing": timing_analysis,
            "harmonic": harmonic_analysis,
            "transient": transient_analysis
        }
        
        # Calculate AI probability
        ai_probability = self._calculate_ai_probability(analysis_details)
        
        # Detect specific artifacts
        artifacts = self._detect_artifacts(analysis_details)
        
        # Determine origin classification
        origin = self._classify_origin(ai_probability, artifacts)
        
        # Calculate overall confidence
        confidence = self._calculate_confidence(analysis_details)
        
        return AIDetectionResult(
            origin=origin,
            ai_probability=ai_probability,
            confidence=confidence,
            analysis_details=analysis_details,
            artifacts_detected=artifacts
        )
    
    def _analyze_spectral_characteristics(self, audio_data: np.ndarray, sr: int) -> dict:
        """
        Analyze spectral characteristics for AI markers.
        
        AI-generated audio often has unnaturally smooth spectra.
        """
        n_fft = min(2048, len(audio_data))
        if len(audio_data) < n_fft:
            audio_data = np.pad(audio_data, (0, n_fft - len(audio_data)))
        
        fft_result = np.fft.rfft(audio_data[:n_fft])
        magnitude = np.abs(fft_result)
        
        # Calculate spectral smoothness (normalized first derivative)
        spectral_diff = np.diff(magnitude)
        smoothness = 1.0 - (np.std(spectral_diff) / (np.mean(np.abs(spectral_diff)) + 1e-10))
        smoothness = min(max(smoothness, 0), 1)
        
        # Calculate spectral entropy (AI tends to have lower entropy)
        magnitude_norm = magnitude / (np.sum(magnitude) + 1e-10)
        entropy = -np.sum(magnitude_norm * np.log2(magnitude_norm + 1e-10))
        max_entropy = np.log2(len(magnitude))
        normalized_entropy = entropy / max_entropy if max_entropy > 0 else 0
        
        return {
            "smoothness": float(smoothness),
            "entropy": float(normalized_entropy),
            "is_suspicious": smoothness > self.artifact_patterns["spectral_smoothness"]
        }
    
    def _analyze_timing_patterns(self, audio_data: np.ndarray, sr: int) -> dict:
        """
        Analyze micro-timing patterns.
        
        Human performances have natural timing variations that AI often lacks.
        """
        # Detect onset candidates using energy envelope
        frame_length = int(0.02 * sr)  # 20ms frames
        hop_length = int(0.01 * sr)    # 10ms hop
        
        if len(audio_data) < frame_length:
            return {
                "variance": 0.0,
                "consistency": 1.0,
                "is_suspicious": False
            }
        
        # Calculate frame energies
        n_frames = (len(audio_data) - frame_length) // hop_length + 1
        energies = []
        for i in range(n_frames):
            start = i * hop_length
            end = start + frame_length
            frame = audio_data[start:end]
            energies.append(np.sqrt(np.mean(frame**2)))
        
        energies = np.array(energies)
        
        # Detect onsets (energy peaks)
        if len(energies) < 3:
            return {
                "variance": 0.0,
                "consistency": 1.0,
                "is_suspicious": False
            }
            
        onset_indices = []
        for i in range(1, len(energies) - 1):
            if energies[i] > energies[i-1] and energies[i] > energies[i+1]:
                if energies[i] > np.mean(energies):
                    onset_indices.append(i)
        
        # Calculate inter-onset intervals
        if len(onset_indices) < 2:
            return {
                "variance": 0.0,
                "consistency": 1.0,
                "is_suspicious": False
            }
            
        intervals = np.diff(onset_indices)
        variance = np.std(intervals) / (np.mean(intervals) + 1e-10)
        consistency = 1.0 - min(variance, 1.0)
        
        return {
            "variance": float(variance),
            "consistency": float(consistency),
            "is_suspicious": variance < self.artifact_patterns["micro_timing_variance"]
        }
    
    def _analyze_harmonics(self, audio_data: np.ndarray, sr: int) -> dict:
        """
        Analyze harmonic structure.
        
        AI-generated audio often has too-perfect harmonic relationships.
        """
        n_fft = min(4096, len(audio_data))
        if len(audio_data) < n_fft:
            audio_data = np.pad(audio_data, (0, n_fft - len(audio_data)))
        
        fft_result = np.fft.rfft(audio_data[:n_fft])
        magnitude = np.abs(fft_result)
        freqs = np.fft.rfftfreq(n_fft, 1/sr)
        
        # Find fundamental frequency (F0) - highest peak in expected range
        valid_range = (freqs >= 80) & (freqs <= 1000)
        if not np.any(valid_range):
            return {
                "regularity": 0.5,
                "is_suspicious": False
            }
            
        valid_magnitude = magnitude.copy()
        valid_magnitude[~valid_range] = 0
        f0_idx = np.argmax(valid_magnitude)
        f0 = freqs[f0_idx]
        
        if f0 < 80:  # No clear fundamental found
            return {
                "regularity": 0.5,
                "is_suspicious": False
            }
        
        # Check harmonic regularity
        harmonic_energies = []
        for n in range(1, 6):  # Check first 5 harmonics
            expected_freq = f0 * n
            closest_idx = np.argmin(np.abs(freqs - expected_freq))
            if closest_idx < len(magnitude):
                harmonic_energies.append(magnitude[closest_idx])
        
        if len(harmonic_energies) < 2:
            return {
                "regularity": 0.5,
                "is_suspicious": False
            }
        
        # Perfect harmonics indicate AI generation
        harmonic_energies = np.array(harmonic_energies)
        regularity = 1.0 - (np.std(harmonic_energies) / (np.mean(harmonic_energies) + 1e-10))
        regularity = min(max(regularity, 0), 1)
        
        return {
            "regularity": float(regularity),
            "is_suspicious": regularity > self.artifact_patterns["harmonic_regularity"]
        }
    
    def _analyze_transients(self, audio_data: np.ndarray, sr: int) -> dict:
        """
        Analyze transient consistency.
        
        AI-generated transients often lack natural variation.
        """
        # Detect transients using derivative of energy
        frame_length = int(0.005 * sr)  # 5ms frames
        hop_length = int(0.0025 * sr)   # 2.5ms hop
        
        if len(audio_data) < frame_length * 2:
            return {
                "consistency": 0.5,
                "is_suspicious": False
            }
        
        n_frames = (len(audio_data) - frame_length) // hop_length + 1
        energies = []
        for i in range(n_frames):
            start = i * hop_length
            end = start + frame_length
            frame = audio_data[start:end]
            energies.append(np.sqrt(np.mean(frame**2)))
        
        energies = np.array(energies)
        
        # Find transient peaks
        energy_diff = np.diff(energies)
        threshold = np.mean(np.abs(energy_diff)) + np.std(np.abs(energy_diff))
        transient_indices = np.where(energy_diff > threshold)[0]
        
        if len(transient_indices) < 2:
            return {
                "consistency": 0.5,
                "is_suspicious": False
            }
        
        # Analyze transient shapes
        transient_shapes = []
        for idx in transient_indices[:10]:  # Analyze up to 10 transients
            if idx > 2 and idx < len(energy_diff) - 2:
                shape = energy_diff[idx-2:idx+3]
                transient_shapes.append(shape)
        
        if len(transient_shapes) < 2:
            return {
                "consistency": 0.5,
                "is_suspicious": False
            }
        
        # Calculate consistency between transient shapes
        similarities = []
        for i in range(len(transient_shapes)):
            for j in range(i + 1, len(transient_shapes)):
                corr = np.corrcoef(transient_shapes[i], transient_shapes[j])[0, 1]
                if not np.isnan(corr):
                    similarities.append(abs(corr))
        
        consistency = np.mean(similarities) if similarities else 0.5
        
        return {
            "consistency": float(consistency),
            "is_suspicious": consistency > self.artifact_patterns["transient_consistency"]
        }
    
    def _calculate_ai_probability(self, analysis: dict) -> float:
        """Calculate overall probability of AI generation."""
        scores = []
        weights = []
        
        # Spectral analysis contribution
        spectral = analysis.get("spectral", {})
        if "smoothness" in spectral:
            # Higher smoothness = more likely AI
            scores.append(spectral["smoothness"])
            weights.append(0.3)
        if "entropy" in spectral:
            # Lower entropy = more likely AI
            scores.append(1.0 - spectral["entropy"])
            weights.append(0.2)
        
        # Timing analysis contribution
        timing = analysis.get("timing", {})
        if "consistency" in timing:
            # Higher consistency = more likely AI
            scores.append(timing["consistency"])
            weights.append(0.25)
        
        # Harmonic analysis contribution
        harmonic = analysis.get("harmonic", {})
        if "regularity" in harmonic:
            # Higher regularity = more likely AI
            scores.append(harmonic["regularity"])
            weights.append(0.15)
        
        # Transient analysis contribution
        transient = analysis.get("transient", {})
        if "consistency" in transient:
            # Higher consistency = more likely AI
            scores.append(transient["consistency"])
            weights.append(0.1)
        
        if not scores:
            return 0.5
        
        # Weighted average
        weighted_sum = sum(s * w for s, w in zip(scores, weights))
        total_weight = sum(weights)
        
        probability = weighted_sum / total_weight if total_weight > 0 else 0.5
        
        # Apply sensitivity adjustment
        adjusted = probability * (0.5 + self.sensitivity / 2)
        
        return min(max(adjusted, 0.0), 1.0)
    
    def _detect_artifacts(self, analysis: dict) -> list:
        """Detect specific AI generation artifacts."""
        artifacts = []
        
        if analysis.get("spectral", {}).get("is_suspicious"):
            artifacts.append("unnatural_spectral_smoothness")
        
        if analysis.get("timing", {}).get("is_suspicious"):
            artifacts.append("mechanical_timing")
        
        if analysis.get("harmonic", {}).get("is_suspicious"):
            artifacts.append("perfect_harmonics")
        
        if analysis.get("transient", {}).get("is_suspicious"):
            artifacts.append("uniform_transients")
        
        return artifacts
    
    def _classify_origin(self, ai_probability: float, artifacts: list) -> AudioOrigin:
        """Classify the origin of the audio based on analysis."""
        threshold = 0.5 + (self.sensitivity - 0.5) * 0.3
        
        if ai_probability > threshold + 0.25:
            return AudioOrigin.AI_GENERATED
        elif ai_probability > threshold:
            if len(artifacts) >= 2:
                return AudioOrigin.AI_ENHANCED
            return AudioOrigin.SOUND_ALIKE
        elif ai_probability > threshold - 0.2:
            return AudioOrigin.UNKNOWN
        else:
            return AudioOrigin.HUMAN
    
    def _calculate_confidence(self, analysis: dict) -> float:
        """Calculate confidence in the detection result."""
        # More data points = higher confidence
        confidence = 0.3  # Base confidence
        
        if "spectral" in analysis:
            confidence += 0.2
        if "timing" in analysis:
            confidence += 0.2
        if "harmonic" in analysis:
            confidence += 0.15
        if "transient" in analysis:
            confidence += 0.15
        
        return min(confidence, 1.0)
